### ISSUE TITLE
RFC: Norwegian as working language

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1054]
When starting this project we valued using English as a working language for communication on Github, User Stories, Features, etc. This to be more accessible for other contributors and for collaboration with other entities within the same domain.

But now, seeing the reality of communication and discussions on issues here and having to translate potential tasks from Miro/Figma/Roadmaps here I think it's time to re-evaluate the initial assumption.

So this proposes a new working language: Norwegian. I don't think everything should be in Norwegian, though. See overview below. I also think we shouldn't rewrite feature descriptions or titles (only those where it might be appropriate).

## In Norwegian:

- Issues, Features, and tasks.
- Comments, QA, code reviews, and suggestions.
- Roadmap descriptions etc.
- Release text descriptions.

## In English:

- Code (variables etc) and code comments.
- Commit messages.
- Pull Request Titles (will be reused for changelog)
- Technical documentation (getting started, contribution guide, etc).

---

This RFC uses the lazy consensus principle. If no one objects within 10 days, we'll go ahead and implement the new standard. I've added people using this code base as reviewers. If there are objections within 10 days we'll solve those objections or ultimately do voting.

**Comment by cbrevik** [comment]
Since we practice squash-on-merge, shouldn't "pull request titles" follow "commit messages" and being in English? Otherwise in practice (from a code history viewpoint) commit messages will be in Norwegian. Also changelogs are pretty internal (they only leak out to TestFlight, etc), so I'm a bit unsure if they actually need to be in Norwegian? The "final" release notes have to be humanized each time anyway. What do you think?

**Comment by mikaelbr** [comment]
Fine by me!
