### ISSUE TITLE
[BUG] Missing formatting for sales tax amount

### ISSUE THREAD

**Issue by havwig** [AtB-AS/mittatb-app#1070]
**Describe the bug**
Sales tax for ticket is formatted as "9.6". Should be two digits and locale (or fixed Norwegian) decimal separator.

**Application version**
Version number: 1.6

**To Reproduce**
1. Go to Tickets
2. Purchase new ticket
3. Note formatting for sales tax

**Expected behavior**
Should be formatted as e.g. "9,60".

**Smartphone (please complete the following information):**
 - Device: Samsung Note 10
 - OS: Android

**Comment by gorandalum** [comment]
Found this bug to only be present on Android, the reason is that the javascript compiler for Android does not support internationalisation (Intl).

If we used the standard javascript engine we could replace it with a version supporting internationalisation:
https://github.com/react-native-community/jsc-android-buildscripts#international-variant

However we are using hermes, which as of now does not support internationalisation. Internationalisation support [is coming](https://github.com/facebook/hermes/issues/23#issuecomment-816126715) with RN 0.65. The release date of RN 0.65 is unknown, but looking at earlier releases the release cycle seems to be between 3-9 months. As RN 0.64 was released this march we can't expect RN 0.65 until at least after the summer.

Some slightly-ordered alternatives:
- Write some code to handle it manually for now
- Just wait it out until RN 0.65
- [Polyfill it](https://github.com/facebook/hermes/issues/23#issuecomment-675098624)
- Use standard jsc engine instead of hermes

Whats your thoughts on this? @havwig @cbrevik @mikaelbr
