### ISSUE TITLE
Reisesøk-pagination med cursor istedet for timestamp

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1963]
Entur har deprecated timestamp-pagination til fordel for cursor-søk.
(endringen er antakelig kosmetisk)

Kun endring i app: To timer

Hvis BFF: Større oppgave med delvise oppdatering av status på søk (separat sak)

**Comment by cbrevik** [comment]
Teste at gåstrekning (ref #1981) ikke kommer opp i hver søke-page

**Comment by cbrevik** [comment]
Fra PR:

- Using the auto-sized search window from Entur instead of using our own
  logic. This search window logic will soonly be improved by Entur with
  logic that increases the search window if few results are returned.
- Support searches by arrival time
- Updated to use pageCursor when using the Entur trips api.
- Made load-more-button visible even though zero results on the
  first load.
- No longer the ScrollView refresh animation after refreshing by
  scrolling down.
- Refreshing by scrolling down now cancels the current search.
- Store searches in "last used searches"
- Cancel previous search when refreshing or changing params
- Fix date bug where the previously selected date was shown even
  though "Travel now" was selected
- Remote config to make it possible to override some search parameters

**Comment by gorandalum** [comment]
Jeg tenker dette blir hovedsaken for reisesøk-otp2, og vi tester i kontekst av denne.

Her bør flere personer teste utforskende i alle kriker og kroker, og med fokus på å prøve brekke noe. Listen over kan brukes som en utgangspunkt, men man kan bruke fantasien for å komme på andre ting som bør testes også enn det som er i listen over.

**Comment by tormoseng** [comment]
Denne er testet nok for nå. Skal ut først i v1.16. Opprettet en egen testsak for denne med lenke til testtips i #2112
