### ISSUE TITLE
[Feature] Notifify customers about known outages in ticketing functionality

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#995]
## Origin

_Links to received feedback, user research or other findings._

## Motivation

Customers trying to buy or display tickets should be notified about known outages that may affect the ticketing functionality in the app. This should be implemented as soon as possible to fulfill the basic needs. The solution may be improved/changed later. 

## Hypotheses and assumptions

This issue assumes that operations staff at AtB is aware of current outages, or planned outages. Automatic submission of messages based on triggers should be considered at a later stage. 

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [ ] Given that an operator has submitted a message, when a user navigates to the ticketing tab in the app, the message should be displayed at the top. 
- [ ] Given that an operator has submitted a message, when the operator clears the message, the message in the ticketing tab in the app should be cleared.

**Comment by gorandalum** [comment]
Main functionality needed for this change:

1. Model for the warnings in FireStore
RemoteConfig is not a good source for these kind of realtime warnings, so FireStore has been proposed as the source instead. We need to model how these warnings should be stored In FireStore. A proposal:
```
{
  title: [
    { lang: 'nor' | 'eng', value: string }
  ],
  body: [
    { lang: 'nor' | 'eng', value: string }
  ],
  type: 'valid' | 'info' | 'warning' | 'error',
  context: 'general' | 'assistant' | 'ticketing'
}
```
Notes:
- For the texts reusing the model for Multilingual string in NeTeX to enable more code reuse
- The type values is the types/statuses in the [design system](https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Theme-1.0?node-id=1%3A873)
- Context may be how fine-grained or coarse-grained we want them to be, to present them in appropriate places in the app/webshop.

This proposal is just to get the discussion started. @mjenssen @torfjor @cbrevik 

2. Design in the app for how the warnings should be presented
Could you look into this @pettersuul? 

3. Method for how the warnings should be added to FireStore.
Since we want this ASAP to fulfil the basic needs, can we for a limited time handle adding/removing warnings manually? @mjenssen @torfjor 
You were looking into what available sources there are for this information @havwig?

@cbrevik You mentioned you had some thoughts on this earlier today, but I do not remember if it was related to point 1, 2 or 3.

**Comment by havwig** [comment]
For the time being I see setting a warning status as a manual operation. It may be possible to automate, e.g. by monitoring the error rate for calls to Entur, but I think we should start out by setting a manual status when we are made aware of any problems.

**Comment by cbrevik** [comment]
Model seems good to me! I'm a bit unsure if we need titles for statuses/alerts though.

As far as thoughts go, I was just thinking if we are going for screen-specific errors, we could extend the header to take a short status:

![image](https://user-images.githubusercontent.com/4932625/110803052-1766c280-827f-11eb-946b-f842801e43d4.png)

This all depends on what @pettersuul thinks of course. But something like that would mean it doesn't matter what tab (buy/valid/expired) you're on in the Ticket-screen.

**Comment by torfjor** [comment]
I can look into getting a really basic CRUD interface up for these. Since we already have auth set up in firebase we could do a check on a custom claim, eg. "role", for allowing access.

**Comment by gorandalum** [comment]
I've implemented a prototype for this now. Is it a little "risky" to have the message box backgrounds see-through? Here the message boxes are in the order `valid`, `info`, `warning` and `error`:
![Screenshot 2021-03-16 at 15 41 22](https://user-images.githubusercontent.com/675421/111328313-6beab300-866e-11eb-8b79-78caed0ece0a.png)
![Screenshot 2021-03-16 at 15 41 04](https://user-images.githubusercontent.com/675421/111328314-6c834980-866e-11eb-89cd-cd05d1b61d71.png)
![Screenshot 2021-03-16 at 15 41 50](https://user-images.githubusercontent.com/675421/111328305-6ab98600-866e-11eb-8e46-e3e6d2d301dc.png)
![Screenshot 2021-03-16 at 15 41 36](https://user-images.githubusercontent.com/675421/111328308-6b521c80-866e-11eb-8d3d-7245e92f4b80.png)

**Comment by gorandalum** [comment]
Note: Added flag active (boolean) to the alert model in Firestore:
https://github.com/AtB-AS/mittatb-app/pull/1010
